### ISSUE TITLE
Aur package?

### ISSUE THREAD

**Issue by Meganium97** [unknownskl/greenlight#198]
I was wondering if you could create an aur package (or I can) for arch linux users.

**Comment by Gustash** [comment]
@Meganium97 I've created [an AUR package](https://aur.archlinux.org/packages/xbox-xcloud).

No git version yet, this installs based on `.deb` releases. I'll do my best to maintain it as updates come through here :) feel free to ping me in AUR comments for that package in case I miss a release

**Comment by unknownskl** [comment]
Aur package is not planned
