### ISSUE TITLE
[Request] Gamepad Force Feedback / Rumble

### ISSUE THREAD

**Issue by MLGMcDonald** [unknownskl/greenlight#330]
Currently, force feedback / rumble does not appear to be functional. Is this something that could be added in a future release?

There does appear to be a GamepadHapticActuator interface in the webkit Gamepad API (https://developer.mozilla.org/en-US/docs/Web/API/GamepadHapticActuator)

Tested:
Windows with an Xbox One controller over Bluetooth
Windows with an Xbox One controller over Xbox Wireless USB.
SteamOS (Steam Deck) native controller
SteamOS (Steam Deck) Xbox One Controller over Bluetooth

**Comment by cgarst** [comment]
Could be tricky as I believe the only instances of rumble working is official clients where the `Windows.Gaming.Input` (or WGI) API is available, e.g. Xbox app on Windows. Here we see Impulse Triggers working which signals more going on than just Xinput, which is what webkit Gamepad API was originally built on. However, I see that some extensions were very recently [added to webkit](https://bugs.chromium.org/p/chromium/issues/detail?id=1316534&q=component%3ABlink%3EGamepadAPI) which may be a useful API on Win10+ machines. It would be interesting to know if it's possible to recognize basic Xinput instructions for rumble, or if pure WGI stuff is the only thing in the stream.

Currently the client is behaving the same way the official Android/iOS/Edge/Chrome clients do, which is not to rumble.

**Comment by unknownskl** [comment]
The newest v2.0.0-beta1 has rumble support for xCloud games. Home-Streaming is currently not working with rumble as it does not send the rumble packets yet.

**Comment by unknownskl** [comment]
Closed due inactivity
