### ISSUE TITLE
Please publish to appimagehub.com or flathub.org

### ISSUE THREAD

**Issue by lwbt** [unknownskl/greenlight#355]
Hello, I just [found out](https://www.reddit.com/r/SteamDeck/comments/uhxio3/xbox_remote_play_on_steam_deck_is_now_possible/ihxxbao/) about this project and wanted to ask for an easier way to install onto SteamDeck. If you don't want to implement Flatpak builds, the easiest way would be to talk to the people on [appimagehub.com](https://www.appimagehub.com/) to get your app included in their catalog so that [appimagepool](https://flathub.org/apps/details/io.github.prateekmedia.appimagepool) can find it, I guess.

**Comment by unknownskl** [comment]
Will do once I get my steam deck in about a month! Want to make sure everything works properly

**Comment by unknownskl** [comment]
Progress has been started on the branch `feature/flatpak`. Got a very first working version working but it still needs some refinement and bug fixes.

**Comment by mmalyska** [comment]
Hi, how is the progress of flatpak?

**Comment by AsciiWolf** [comment]
Flatpak support would be great. :-)

**Comment by unknownskl** [comment]
Having some issues with automating the npm sources and yarn sources (Especially yarn is a pain to work with so far). Just found this repo which may help resolving the issue: https://github.com/flatpak/flatpak-builder-tools/tree/master/node

**Comment by AsciiWolf** [comment]
Consider [submitting](https://docs.flathub.org/docs/for-app-authors/submission/) the Flatpak manifest file directly to [Flathub](https://flathub.org). They have their own build infrastructure + target most end-users since Flathub is considered the main Flatpak repository and as such is available out-of-box on many distributions including SteamOS.

**Comment by unknownskl** [comment]
Experimental .flatpak file will be provided with the next build (non-tested). Expect a lot of bugs still as i havent tried the gamepad or streaming capabilities yet.

**Comment by alistair23** [comment]
Any update on this? I am happy to help test but can't seem to find where the build artifacts are

**Comment by Movisivi** [comment]
There are none.  Best use https://flathub.org/apps/io.github.mandruis7.xbox-cloud-gaming-electron for now

**Comment by Movisivi** [comment]
There is a flatpak at https://github.com/unknownskl/greenlight/actions/runs/7126053832 but I can't seem to install it

**Comment by unknownskl** [comment]
Thanks for the patience! Greenlight can now be found on Flathub 🎉 https://flathub.org/apps/io.github.unknownskl.greenlight
