### ISSUE TITLE
Flatpack support

### ISSUE THREAD

**Issue by ghostekpl** [unknownskl/greenlight#369]
It would be cool if the next release is released as a flatpack and added to the discovery store in steam deck

**Comment by monreal** [comment]
I would also love a flatpak, distributed on flathub.

**Comment by unknownskl** [comment]
Linked to #355

**Comment by AsciiWolf** [comment]
It is Flatpak, not Flatpack. And there is already a ticket for this, as mentioned in the previous comment.

**Comment by unknownskl** [comment]
Thanks for the patience! Greenlight can now be found on Flathub 🎉 https://flathub.org/apps/io.github.unknownskl.greenlight
