### ISSUE TITLE
Remote Play Desync after inactive on ethernet

### ISSUE THREAD

**Issue by trashbus99** [unknownskl/greenlight#379]
After maybe 60 seconds of inactivty, the client's video desyncs from the stream..if you move the stick you can hear the cursor moving around, but the video shows no change in the image.  (seems to happen even sooner/more frequently on wifi)

**Comment by MisterAnderson91** [comment]
What platform are you using xbox-xcloud-client on, and what version xbox console?

**Comment by trashbus99** [comment]
Tried on both Linux and Windows.  Xbox Series S.

**Comment by unknownskl** [comment]
Please try v2.0.0-beta1 and check if that fixes the problems. The video and audio streams has been greatly improved.

**Comment by trashbus99** [comment]
> Please try v2.0.0-beta1 and check if that fixes the problems. The video and audio streams has been greatly improved.

So it is more stable, but I'm getting more artifacts in the stream and sometimes the decidubg entire screen turns green, etc.

**Comment by ilyachch** [comment]
I've noticed the lag on wifi (both devices connected with same network and 5 Hhz) almost from the very beginning (about 10 seconds after connection to console)

tried v2.0.0-beta1 - it does not allow to login (as I'm not in a supported country)
v1.2.0 - works fine, except the video lag

tried options:
changed server, connected controller with cable to client device, connected controller with radio to xbox - same result. The sound of buttons is instant, but not picture.
The strange behavior is that the stream itself works fine, no artifacts or lost frames (launched Doom 1993 and waited until gameplay demo)

OS: Linux
Installed with Appimage

<details>
<summary>logs</summary>

```
Bootstrapping Xbox-xCloud-Client using args: [ '/tmp/.mount_Xbox-xcAxCfV/xbox-xcloud', '--help' ]
Updater.ts - Checking for updates...
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
tokenStore: e {
  _web: { uhs: '', userToken: '' },
  _streamingToken: '',
  _xCloudStreamingToken: '',
  _xCloudRegionHost: '',
  _xCloudRegions: [],
  _msalToken: '',
  _eventOnWebToken: [ [Function (anonymous)] ],
  _eventOnStreamingToken: [ [Function (anonymous)] ],
  _eventOnxCloudStreamingToken: [ [Function (anonymous)] ],
  _eventOnMSALToken: [ [Function (anonymous)] ],
  _eventOnMSALData: [ [Function (anonymous)] ]
}
Updater.ts - Got response. Current version: 1.2.0
Updater.ts - We got the latest version already.
web tokens set
Requesting xHome and xCloud tokens..
- Error while retrieving xCloud token
  statuscode: 403
  body: {"code":"InvalidCountry","statusCode":403,"message":""}
xhome tokens set
```

</details>

**Comment by unknownskl** [comment]
Is this issue still relevant on the newest beta release? (v2.0.0-beta6)
