### ISSUE TITLE
Video freezes every few minutes. Audio and Controls still work

### ISSUE THREAD

**Issue by Emblazoned1** [unknownskl/greenlight#399]
For some reason my video keeps freezing. Freezes for around 5 to 10 seconds then comes back. Playing on steam deck. Using the latest version. Anyone have a fix for this? Tried both full screen and windowed mode but no luck. Also have no sandbox command in launch options.

**Comment by unknownskl** [comment]
The v1 client has quite some performance issues. Can you try out the new 2.0.0-beta1 release? The audio and video has been greatly improved in that version.
