### ISSUE TITLE
支持肩键与左右摇杆的映射

### ISSUE THREAD

**Issue by lwoldt** [unknownskl/greenlight#409]
您好，是否支持肩键与左右摇杆的映射呢
如果自己想改键盘映射，如何修改

**Comment by unknownskl** [comment]
There is currently no separate mapping for the right joystick. The left joystick can be used using the arrow keys.
The shoulder buttons are mapped to `[` and `]`. (Left and right perspectively). Does that answer your question?

**Comment by lwoldt** [comment]
LT与RT的映射是否存在呢

**Comment by unknownskl** [comment]
No mapping for LT and RT. Will look into it if it is quite easy to enable, could be nice for slow paced games.

**Comment by unknownskl** [comment]
Added mapping, check the Readme for the keys. Closing the issue.
