### ISSUE TITLE
Create template for Issues

### ISSUE THREAD

**Issue by MisterAnderson91** [unknownskl/greenlight#412]
This project seems to be picking up users and has multiple platforms supported.

Recommend implementing an issue template to request the following info for new issues:

- App version installed (e.g. Greenlight-2.0.0-beta1.AppImage)
- OS version (e.g. Windows 11, macOS 12.5, Ubuntu 22.04, Steam Deck)

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by unknownskl** [comment]
Yep, good idea. I've also opened up the discussions board to the public.

**Comment by unknownskl** [comment]
Issue templates have been added!
