### ISSUE TITLE
[Steam Deck] v2.0.0-beta1 not working in game mode.

### ISSUE THREAD

**Issue by Akukuk** [unknownskl/greenlight#423]
Hey. Appimage not launching in game mode. Desktop mode works great. Keep doing good job mate:)

**Comment by unknownskl** [comment]
Hey there! Have you tried to add the game via the start menu instead of the appimage directly? I was a bit confused too but that seemed to do the trick for me. Will add it to the readme.

**Comment by Akukuk** [comment]
Hey. Thanks for replaying. Im new in Linux community, what do you mean by adding it via start menu (extracted win version and added exe?? Or somehow extract appimage??) ?? Little guide how to do it would be great 😃 of course if you got time to do it.

**Comment by unknownskl** [comment]
Ahh, just to make sure; Do you use Windows or SteamOS on the deck?

If you are using the default SteamOS, this guide is pretty useful: https://youtu.be/nC1nhntHkkw (at 5:15 you can see what I meant with adding it via the start menu)
If you are using windows then try the full screen switch `--fullscreen` on the launch parameters (this is also shown in the video above)

**Comment by Akukuk** [comment]
I was doing exactly this. Didn't get it to work but today it started to work dunno why.... But version 2.0 didn't fix imput lag. Gonna stick with 1.2 working much better at this moment at least in my network.

**Comment by Jbbrack03** [comment]
This does work perfectly with the latest beta release on Steam Deck. You have to first install appimagelauncher and then use the Steam Launch Arguments:

--no-sandbox --fullscreen

Full Guide here:
https://www.reddit.com/r/SteamDeck/comments/wbjgmq/guide_setup_xbox_remote_play/
