### ISSUE TITLE
Build instructions/appimage for armhf/arm64?

### ISSUE THREAD

**Issue by MisterAnderson91** [unknownskl/greenlight#429]
I've tested building v1.2.0 on a raspberry pi 400 and it's possible to build and run, although performance is rough.

I built this from the github repo clone.

I'm unsure how to build the v2.0.0-beta1 version from the source download .zip which has a README indicating to run "yarn" which fails. I'm not really expecting this to be usable but I'm interested in whether it works.

**Comment by unknownskl** [comment]
Do you have the yarn package manager installed? You can install it using npm: `npm install -g yarn` (-g installs it globally so you can use `yarn` on the cli)
2.0.0 should run a bit lighter compared to 1.2.x as we dont have to unpack the data stream and feed it to the video component.

**Comment by keanu30** [comment]
need arm64 deb too

**Comment by MisterAnderson91** [comment]
I didn't know what I was doing with npm or yarn, but honestly I've given up interest (I now have a steam deck I'm using) so I'm going to close this issue.
