### ISSUE TITLE
[Request] Ability to launch an xcloud title from the command line

### ISSUE THREAD

**Issue by duwial** [unknownskl/greenlight#457]
Would it be possible to launch an xcloud title from the command line? I think this would be nice have on the steam deck as it would add the possibility to add separate games to steam.

**Comment by shoesio** [comment]
This would be awesome

**Comment by lotherk** [comment]
also to directly start streaming from an xbox

**Comment by unknownskl** [comment]
Closing issue as this is already implemented in a couple versions ago. Instructions are in the readme.
