### ISSUE TITLE
Launch Option --connect== not working with 2.0

### ISSUE THREAD

**Issue by Distant2k** [unknownskl/greenlight#509]
While this was fine in 1.2, I don't seem to get able to get it working in 2.0

**Comment by unknownskl** [comment]
Correct, this functionality is not yet implemented in the 2.0.0 version.

**Comment by Rumik** [comment]
Hi there. Any plans to get the auto connect working again soon?

**Comment by unknownskl** [comment]
Has been added a while ago. Closing the issue.
