### ISSUE TITLE
Error in xcloud tab on steam deck

### ISSUE THREAD

**Issue by DonJaviJr** [unknownskl/greenlight#511]
First off great work on Greenlight.. I live in US and have Xbox game pass ultimate..  I installed your program on my steam deck.. remote play to my Xbox series X is great .. low latency is amazing ... But I am having problems connecting to game pass ... When I click on xcloud tab it tries to load library and gives an error.. 
![20221026_164523](https://user-images.githubusercontent.com/116849798/198412488-3a051315-948e-4b81-91e1-c2c738a3fcb5.jpg)
Do you know what might be causing this... Hope their is a fix.. because this is a perfect application.. thanks..

**Comment by fbloise** [comment]
I'm having this same problem

**Comment by nabel0** [comment]
Same problem here since two days...Was working fine before

**Comment by unknownskl** [comment]
Can you try the new v2.0.0-beta2? There were some fixes for selecting the market.
