### ISSUE TITLE
Skip update notifier possible?

### ISSUE THREAD

**Issue by sam0th** [unknownskl/greenlight#519]
Hi, just asking, it works great with the latest 1.x version with auto connect to my xbox, but it always tells me to update. i have testet the 2.x version but want to stay at the older one as long autoconnect isnt working there.

so i ask if its possible to skip this notification maybe through commandline parameter?

thanks for the good work, great app!

**Comment by unknownskl** [comment]
Do you have the latest stable version of 1.2.0? The stable version should not notify on new beta releases. Maybe try to reinstall it again: https://github.com/unknownskl/xbox-xcloud-client/releases/tag/v1.2.0

**Comment by unknownskl** [comment]
Closing issue due inactivity
