### ISSUE TITLE
Only works when launched directly on Steamdeck

### ISSUE THREAD

**Issue by diehardbattery** [unknownskl/greenlight#542]
This isn't working for me. I installed AppImageLauncher and it runs fine directly in desktop mode. It will not start in either steam desktop app or game mode. In game mode, I get a spinning Steam logo for about 2 minutes and quits. I have added the "run --fullscreen --no-sandbox" options with no joy. I've also run the app directly in desktop mode so I can authenticate but running it from either steam desktop app or game mode is a no go.

**Comment by OStogden** [comment]
Can confirm I also have this issue. Running the Appimage works, but going through Steam fails.

**Comment by RidleyDeckard** [comment]
I can confirm it does work; you haven't specified the launch options in Steam under properties. You need to add:
--no-sandbox --fullscreen
Just add this and you should be fine

**Comment by diehardbattery** [comment]
For me, I had those already.  But for some reason it just started working... weird.

**Comment by unknownskl** [comment]
Greenlight is also released on flathub which should make it easier to install and update the application. If the problem persists then please reopen the issue.
