### ISSUE TITLE
Flatpak distribution

### ISSUE THREAD

**Issue by fpiesche** [unknownskl/greenlight#568]
As I've just done this for another project (RBDoom3BFG), I'm going to go and set up a Flatpak build for this so that it can just be found in the Discover store on the Steam Deck and included in the Deck's automated system update process.

Maintenance work for this will be minimal - Flatpak builds consist mostly of a yaml or json file specifying build instructions and dependencies, a .desktop file and icon and a metadata XML. The process for this is to fork Flathub's main repository, adding the relevant data to a branch and submitting a PR for inclusion which will then just be built and listed on Flathub as and when appropriate.

However, Flathub's submission guidelines explicitly say that for third-party submissions permission from the project maintainers should be sought - so this is me doing exactly that. Does having a Flatpak build of the client sound good to you? :)

**Comment by martijn1899** [comment]
Flatpack would be great! Easy install and update.

**Comment by electroflame** [comment]
Did anything ever come of this?  Having just installed Greenlight on a Steam Deck myself, a Flatpak build would be great compared to either installing it manually, or installing it with AppImageLauncher.

Not to say that it's difficult with either of those options, but the Flatpak build would make it significantly easier to keep this up-to-date along with the rest of the Steam Deck's software.  It'd also make it much easier for less technically-inclined users who don't want to (or can't easily) use the terminal.

**Comment by unknownskl** [comment]
Progress has been started on the branch `feature/flatpak`. Got a very first working version working but it still needs some refinement and bug fixes.

Linked to #355

**Comment by fpiesche** [comment]
Duplicate of #355.
