### ISSUE TITLE
'ISDEV'  is not recognized as an internal or external command

### ISSUE THREAD

**Issue by yuri921** [unknownskl/greenlight#591]
> ISDEV=true electron-forge start

'ISDEV'  is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Xbox-xCloud@1.2.0 start: `ISDEV=true electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Xbox-xCloud@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-11-22T05_00_45_766Z-debug.log

**Comment by MisterAnderson91** [comment]
Try updating to the v2.0.0-beta2 release if you are running v1.2.0.
