### ISSUE TITLE
Can't go full screen

### ISSUE THREAD

**Issue by Ahmed-M0rsy** [unknownskl/greenlight#595]
Devices:
MacBook Pro 13-inch, M1, 2020
MacOS Venture 13.0.1 (22A400)

Xbox Series S
10.0.22621.2859 (xb_fit_2211ni.221115-2145)

**Comment by MisterAnderson91** [comment]
This is fixed in the v2.0.0-beta2 release (and beta1). The whole app is significantly better and is renamed "Greenlight".

Delete the old xbox-xcloud-client.app file from Applications and download and install the beta2 release from the Releases page.
