### ISSUE TITLE
[Mac] Audio = mono

### ISSUE THREAD

**Issue by johbir** [unknownskl/greenlight#654]
I've been using the latest 2.0.0-beta2 build, and the audio is only mono for now. This happens on both Remote Play and via Xbox Cloud Gaming. The audio output from the Xbox is set to stereo.

**Comment by unknownskl** [comment]
Thanks, this should be implemented in the player. I've created an issue to keep track here: https://github.com/unknownskl/xbox-xcloud-player/issues/106

**Comment by unknownskl** [comment]
Stereo has been fixed. Closing the issue
