### ISSUE TITLE
Use webui plugin with 2.0.0 release

### ISSUE THREAD

**Issue by webqap** [unknownskl/greenlight#673]
Thanks for all the hard work.

Is it possible to use the webui plugin with the latest (2.0.0) release?

Right now the option only seems available in the older 1.2.0 version.

**Comment by blitz2kx** [comment]
Seconded! This feature was great.

Now that Nvidia has launched VSR with its drivers, the video quality in the browser can be upscaled to HD levels. Tried it out with 1.20 and it looks incredible. Hoping to see this come back in the latest release with all of the new features such as rumble.

Cheers!

**Comment by unknownskl** [comment]
Progress on the Web UI has been started and is expected to be released somewhere later this month.

**Comment by unknownskl** [comment]
The WebUI feature is back in the new v2.2.0 release. You can find the option in Settings -> WebUI.
