### ISSUE TITLE
Steam (Deck) - Add instructions to make it reliably work when launching through the Steam Client

### ISSUE THREAD

**Issue by TopHatHipster** [unknownskl/greenlight#718]
To boot Greenlight's AppImage (tested `2.0.0-beta2`), you will need to have `LD_PRELOAD= %command%` in the Launch Options (Game shortcut's properties menu leads you to where you can put it in). Additional commands such as `--fullscreen --connect=<consoleID>` need to be put *after* `%command%`.

Would it be possible to add this instruction in the `README.md`, under the Steam Deck section?

**Comment by Jademalo** [comment]
Just to add, in my experience `--no-sandbox` as a standard launch argument also seems to work.

**Comment by gunnaraas** [comment]
Can confirm, latest build requires `LD_PRELOAD= %command%` for the application to launch properly from the Steam Deck UI (works in Desktop). 

I'll put together a PR to get the README edited, though this seems like it might be a bug in need of fixing.

**Comment by unknownskl** [comment]
Greenlight is released on flathub now which should makes things a lot more easier. :)
