### ISSUE TITLE
TransferTokenPackageDecryptFailed - XCloud games

### ISSUE THREAD

**Issue by lasagneking** [unknownskl/greenlight#732]
I have local play working fine although when attempting Xplay, I always get the following message after choosing a game from the list.  I’ve tried 40-50 different games and I get the same message for all of them.

I’ve tried restarting the application as well as logging out and back in again but nothing seems to work.

Error in Promise: {"state":"Failed", "errorDetails": {"code":"Unknown","message":"Type: UserError:

Internal Code :TransferTokenPackageDecryptFailed: Details Failed to sign in with transfer token, perhaps due to invalid transfer token from the client Fault: [-2147215358 at xbox\\streaming\

\managementservice\\server\\addandsigninuserv2operation.cpp: 72\tclass Network::AddAndSignInUserV2Command failed.]"}}

Ok

**Comment by unknownskl** [comment]
Please try the new 2.0.0-beta3 release. It should have fixed the error :)

**Comment by lasagneking** [comment]
Yes, Xcloud now works perfectly, thanks for your work 👍
